spring.application.name=CentralAPI
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
auth.base-url=${AUTH_BASE_URL:http://auth-api:8080}
player.base-url=${PLAYER_BASE_URL:http://player-api:8080}
monster.base-url=${MONSTER_BASE_URL:http://monster-api:8080}
invocation.base-url=${INVOCATION_BASE_URL:http://invocation-api:8080}

# Swagger UI
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

# Un peu de tri/ergonomie
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true

# Actuator (mappings)
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.mappings.enabled=true
management.endpoint.health.show-details=always