spring.application.name=AuthAPI
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

jwt.secret=change-me-change-me-change-me-change-me-change-me-change-me-change-me-1234567890abcdef
jwt.expiration-ms=3600000